// src/App.tsx
import { Suspense } from 'react';
import { Routes, Route } from 'react-router-dom';
import LoadingScreen from './components/LoadingScreen';
import MainView from './views/MainView';

export default function App() {
  return (
    <Suspense fallback={<LoadingScreen />}>
      <Routes>
        <Route path="/" element={<MainView live={false} />} />
        <Route path="/live" element={<MainView live={true} />} />
      </Routes>
    </Suspense>
  );
}

// src/App.vue
<script setup>
import { RouterView } from 'vue-router';
import LoadingScreen from './components/LoadingScreen.vue';
</script>

<template>
  <RouterView v-slot="{ Component }">
    <template v-if="Component">
      <Transition mode="out-in">
        <KeepAlive>
          <Suspense>
            <component :is="Component"></component>
            <template #fallback>
              <LoadingScreen />
            </template>
          </Suspense>
        </KeepAlive>
      </Transition>
    </template>
  </RouterView>
</template>
